[package]
name = "file_renamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rng = "0.1.0"
clap = "3.0"
